version: "3.1"

services:
  clickhouse:
    container_name: extrnode-clickhouse
    image: "clickhouse/clickhouse-server:23.1"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse:/var/lib/clickhouse
      - ./build/clickhouse:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: "50m"

volumes:
  clickhouse: