version: "3.1"

services:
  postgres:
    container_name: extrnode-postgres
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASS}"
      POSTGRES_DB: "${PG_DB}"
    volumes:
      - postgres:/var/lib/postgresql/data
    logging:
      options:
        max-size: "50m"

volumes:
  postgres: